version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres15
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_anWg1zJh3csu
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neondb_owner"]
      interval: 10s
      retries: 5

volumes:
  pgdata:
